package com.hello1.helloproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HelloAlert implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public HelloAlert() {
    }




}